name: Build App iOS

on:
  workflow_call:
    inputs:
      SCHEME:
        required: true
        type: string
      CONFIGURATION:
        required: true
        type: string
      DESTINATION:
        required: true
        type: string
      # ORG_NAME:
      #   required: true
      #   type: string
      # PROJECT_NAME:
      #   required: true
      #   type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: SHOW ENVIROMENTS VAIRABLES
        run: |
          # -------> Show Variables:
          echo "${{ inputs.SCHEME }}"
          echo "${{ inputs.CONFIGURATION }}"
          echo "${{ inputs.DESTINATION }}"

      - name: Build App with Xcode
        run: |
          # ------------> Buildando aplicação ...
          echo "xcodebuld --scheme $SCHEME --configuration $CONFIGURATION --destination $DESTINATION"