name: Build App iOS

on:
  workflow_call:
    # inputs:
    #   SCHEME:
    #     required: true
    #     type: string
    #   CONFIGURATION:
    #     required: true
    #     type: string
    #   DESTINATION:
    #     required: true
    #     type: string
    #   ORG_NAME:
    #     required: true
    #     type: string
      # PROJECT_NAME:
      #   required: true
      #   type: string

jobs:
  build:
    runs-on: macos-latest


    steps:
      - name: Load Variables
        uses: actions/download-artifact@v4
        with:
          name: shared-variables

      - name: Test Downloded Artifacts
        run: |
          ls -R
          cat variables.yaml
      # - name: install yq
      #   run: brew install yq

      - name: Ler variável
        run: |

          export SCHEME=$(yq -r .SCHEME variables.yaml)
          export CONFIGURATION=$(yq -r .CONFIGURATION variables.yaml)
          export DESTINATION=$(yq -r .DESTINATION variables.yaml)
          echo "---------------------------"
          echo "#------- GET VALUES FROM YAML --------"
          echo "1. $SCHEME"
          echo "2. $CONFIGURATION"
          echo "3. ${DESTINATION}"
          
          echo "SCHEME=$SCHEME" >> $GITHUB_ENV
          echo "CONFIGURATION=$CONFIGURATION"  >> $GITHUB_ENV
          echo "DESTINATION=${DESTINATION}"  >> $GITHUB_ENV

      # - name: SHOW ENVIROMENTS VAIRABLES
      #   run: |
      #     # -------> Show Variables:
      #     echo "${{ inputs.SCHEME }}"
      #     echo "${{ inputs.CONFIGURATION }}"
      #     echo "${{ inputs.DESTINATION }}"
      #     echo "${{ env.ORG_NAME }}"
      
      - name: Checkkout Code
        uses: actions/checkout@v4
  
      - name: Build App with Xcode
        run: |
          # ------------> Buildando aplicação ...
          echo "xcodebuld \ 
            --scheme $SCHEME \ 
            --configuration $CONFIGURATION \
            --destination $DESTINATION"


        # env:
        #   SCHEME: ${{ inputs.SCHEME }}
        #   CONFIGURATION: ${{ inputs.CONFIGURATION }}
        #   DESTINATION: ${{ inputs.DESTINATION }}
