name: Build App iOS

on:
  workflow_call:
    # inputs:
    #   SCHEME:
    #     required: true
    #     type: string
    #   CONFIGURATION:
    #     required: true
    #     type: string
    #   DESTINATION:
    #     required: true
    #     type: string
    #   ORG_NAME:
    #     required: true
    #     type: string
      # PROJECT_NAME:
      #   required: true
      #   type: string

jobs:
  build:
    runs-on: macos-latest


    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shared-variables

      - name: Test Downloded Artifacts
        run: |
          ls -R
          cat variables.yml
      # - name: install yq
      #   run: brew install yq

      - name: Ler variável
        run: |
          yq
          yq e .SCHEME variables.yml
          yq e .CONFIGURATION variables.yml
          yq e .DESTINATION variables.yml

          # MY_VARIABLE=$(cat variable.txt)
          # echo "Variável compartilhada: $MY_VARIABLE"

      # - name: SHOW ENVIROMENTS VAIRABLES
      #   run: |
      #     # -------> Show Variables:
      #     echo "${{ inputs.SCHEME }}"
      #     echo "${{ inputs.CONFIGURATION }}"
      #     echo "${{ inputs.DESTINATION }}"
      #     echo "${{ env.ORG_NAME }}"
      
      - name: Checkkout Code
        uses: actions/checkout@v4
  
      - name: Build App with Xcode
        run: |
          # ------------> Buildando aplicação ...
          echo "xcodebuld --scheme $SCHEME --configuration $CONFIGURATION --destination $DESTINATION"
        # env:
        #   SCHEME: ${{ inputs.SCHEME }}
        #   CONFIGURATION: ${{ inputs.CONFIGURATION }}
        #   DESTINATION: ${{ inputs.DESTINATION }}
