name: deploy

on:
  workflow_call:
    inputs:
      # APP_NAME:
      #   required: true
      #   type: string
      # AUTOR:
      #   required: true
      #   type: string
      # DATE:
      #   required: true
      #   type: string
      ORG_NAME:
        required: true
        type: string

      # ORG_NAME:
      #   required: true
      #   type: string
      # PROJECT_NAME:
      #   required: true
      #   type: string

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: DISPLAY VARS
        run: |

          echo "----------------------------------------------"

          echo "ORG_NAME =====> ${{ inputs.ORG_NAME }}"

