name: 'App Test With Inputs'

env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Steve Jobs'
  DATE: '22/04/2025'

on:
  push
  
jobs:
  job_00:
    runs-on: macos-latest
    outputs:
      APP_NAME: ${{ steps.set-variables.outputs.APP_NAME }}
      AUTOR: ${{ steps.set-variables.outputs.AUTOR }}
      DATE: ${{ steps.set-variables.outputs. DATE }}

    steps:
    - name: set variables
      id: set-variables
      run: |
        echo "APP_NAME=${{ env.APP_NAME }}" >> GITHUB_OUTPUT
        echo "AUTOR=${{ env.AUTOR }}" >> GITHUB_OUTPUT
        echo "DATE=${{ env.DATE }}" >> GITHUB_OUTPUT



    - name: job 00
      run: |
        echo ${{ env.APP_NAME }}
        echo ${{ env.AUTOR }}
        echo ${{ env.DATE }}
        echo "----------------------------------"


  job_01:
    needs: job_00
    uses: ./.github/workflows/prerequisites.yml


  job_02:
    needs: job_00
    runs-on: macos-latest
    steps:
      - name: Display Variables
        run: |
          echo "---------------> test"
          echo ${{ needs.job_00.outputs.APP_NAME }}
          echo ${{ needs.job_00.outputs.AUTOR }}
          echo ${{ needs.job_00.outputs.DATE }}
