name: 'App Test With Inputs'


on:
  push
  
env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Fulano de Tal'
  DATE: '22/04/2025'

jobs:
  start:
    uses: ./.github/workflows/prerequisites.yml
    with:
      APP_NAME: ${{ env.APP_NAME }}
      AUTOR: ${{ emv.AUTOR }}
      DATE: ${{ env.DATE }}
    
  init:
    runs-on: macos-latest
    steps:
      - name: init test
        run: |
          echo "---------------> test"
