name: 'App Test With Inputs'

env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Fulano de Tal'
  DATE: '22/04/2025'

on:
  push
  
jobs:
  job_00:
    runs-on: macos-latest
    steps:
    - name: job 00
      run: |
        echo ${{ env.APP_NAME }}
        echo ${{ env.AUTOR }}
        echo ${{ env.DATE }}

  job_01:
    needs: job_00
    uses: ./.github/workflows/prerequisites.yml
    secrets: inherit

  job_02:
    needs: job_01
    runs-on: macos-latest
    steps:
      - name: test
        run: |
          echo "---------------> test"
          echo ${{ env.APP_NAME }}
