name: 'App Test With Inputs'

on:
  push

jobs:
  start:
    uses: ./.github/workflows/prerequisites.yml@main
    
  init:
    runs-on: macos-latest
    steps:
      - name: init test
        run: |
          echo "---------------> test"
