name: 'App Test With Inputs'

env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Fulano de Tal'
  DATE: '22/04/2025'

on:
  push
  

jobs:
  start:
    uses: ./.github/workflows/prerequisites.yml
    with:
      APP_NAME: ${{ env.APP_NAME }}
      AUTOR: ${{ env.AUTOR }}
      DATE: ${{ env.DATE }}nv   
  init:
    runs-on: macos-latest
    steps:
      - name: init test
        run: |
          echo "---------------> test"
