name: 'App Test With Inputs'

env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Steve Jobs'
  DATE: '22/04/2025'

on:
  push
  
jobs:
  job_00:
    runs-on: macos-latest
    outputs:
      APP_NAME: ${{ steps.set-variables.outputs.APP_NAME }}
      AUTOR: ${{ steps.set-variables.outputs.AUTOR }}
      DATE: ${{ steps.set-variables.outputs. DATE }}

    steps:
    - name: set variables
      id: set-variables
      run: |
        echo "APP_NAME=${{ env.APP_NAME }}" >> "$GITHUB_OUTPUT"
        echo "AUTOR=${{ env.AUTOR }}" >> "$GITHUB_OUTPUT"
        echo "DATE=${{ env.DATE }}" >> "$GITHUB_OUTPUT"
        echo "-------------------------------------------------"
        echo ${{ env.APP_NAME }}
        echo ${{ env.AUTOR }}
        echo ${{ env.DATE }}

    # - name: job 00
    #   run: |
    #     echo ${{ env.APP_NAME }}
    #     echo ${{ env.AUTOR }}
    #     echo ${{ env.DATE }}
    #     echo "----------------------------------"


  job_01:
    needs: job_00
    uses: ./.github/workflows/prerequisites.yml
    with:
      APP_NAME: ${{ needs.job_00.outputs.APP_NAME }}
      AUTOR: ${{ needs.job_00.outputs.AUTOR }}
      DATE: ${{ needs.job_00.outputs.DATE }}


  job_02:
    needs: job_01
    runs-on: macos-latest
    steps:
      - name: Display Variables
        run: |
          echo "----- Variables: --------"
          echo "$APP_NAME // $AUTOR // $DATE"

        env:
          APP_NAME: ${{ needs.job_00.outputs.APP_NAME }}
          AUTOR: ${{ needs.job_00.outputs.AUTOR }}
          DATE: ${{ needs.job_00.outputs.DATE }}
