name: 'App Test With Inputs'

env:
  APP_NAME: 'app-test-ios-develop'
  AUTOR: 'Fulano de Tal'
  DATE: '22/04/2025'

on:
  push
  

jobs:
  start:
    uses: ./.github/workflows/prerequisites.yml
    # with:
    #   app-name: ${{ env.APP_NAME }}
    #   autor: ${{ env.AUTOR }}
    #   date: ${{ env.DATE }}
  init:
    runs-on: macos-latest
    steps:
      - name: init test
        run: |
          echo "---------------> test"
          echo ${{ env.APP_NAME }}
