name: prerequisites

on:
  workflow_call:
    inputs:
      PROJECT_ID:
        required: true
        type: string
      AMBIENT:
        required: true
        type: string
      LOCAL:
        required: true
        type: string
      ORG:
        required: true
        type: string

jobs:
  prereqs:
    runs-on: macos-latest

    steps:
      - name: Show Variables
        run: |

          echo "----------------------------------------------"
          echo "${{ inputs.APP_NAME }}"
          echo "${{ inputs.AUTOR }}"
          echo "${{ inputs.DATE }}"