name: prerequisites

on:
  workflow_call:
    inputs: { }
      # APP_NAME:
      #   required: true
      #   type: string
      # AUTOR:
      #   required: true
      #   type: string
      # DATE:
      #   required: true
      #   type: string
      # ORG_NAME:
      #   required: true
      #   type: string
      # PROJECT_NAME:
      #   required: true
      #   type: string

jobs:
  prereqs:
    runs-on: macos-latest

    steps:
      - name: DISPLAY VARS
        run: |

          echo "----------------------------------------------"

          # echo "${{ inputs.APP_NAME }}"
          # echo "${{ inputs.AUTOR }}"
          # echo "${{ inputs.DATE }}"
          echo "ORG_NAME ----> ${{ inputs.ORG_NAME}}"
          echo "ORG_NAME ----> $ORG_NAME"
          # echo "${{ inputs.PROJECT_NAME }}"