name: prerequisites

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      AUTOR:
        required: true
        type: string
      DATE:
        required: true
        type: string


jobs:
  set-variables:
    runs-on: macos-latest

    steps:
      - name: Show Variables
        run: |

          echo "----------------------------------------------"
          echo "${{ inputs.APP_NAME }}"
          echo "${{ inputs.AUTOR }}"
          echo "${{ inputs.DATE }}"